src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhotoRepository::class)
 */
class Photo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="photos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $uploaded_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_public;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeInterface
    {
        return $this->uploaded_at;
    }

    public function setUploadedAt(\DateTimeInterface $uploaded_at): self
    {
        $this->uploaded_at = $uploaded_at;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }
}

src/Controller/MyController.php
<?php

namespace App\Controller;

use App\Entity\Photo;
use App\Service\PhotoVisibilityService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class MyController
 * @package App\Controller
 * @IsGranted("ROLE_USER")
 */


class MyController extends AbstractController
{
    /**
     * @Route("/my/photos", name="my_photos")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $myPhotos = $em->getRepository(Photo::class)->findBy(['user' => $this->getUser()]);
        return $this->render('my/index.html.twig', [
            'myPhotos' => $myPhotos
        ]);
    }

    /**
     * @Route("/my/photos/set_visibility/{id}/{visibility}", name="my_photos_set_visibility")
     * @param PhotoVisibilityService $photoVisibilityService
     * @param int $id
     * @param bool $visibility 
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function myPhotoChangeVisibility(PhotoVisibilityService $photoVisibilityService, int $id, bool $visibility){
        $messages = [
            '1' => 'publiczne',
            '0' => 'prywatne'
        ];
        if($photoVisibilityService->makeVisible($id, $visibility)){
            $this->addFlash('succes', 'Ustawiono jako '.$messages[$visibility].'.');
        } else {
            $this->addFlash('error', 'Wystąpił problem przy ustawianiu jako '.$messages[$visibility].'.');
        }

        return $this->redirectToRoute('my_photos');
    }

    /**
     * @Route("/my/photos/remove/{id}", name="my_photos_remove")
     * @param int $id
     * @return \Symfony\Component\HttpFundation\RedirectResponse
     */
    public function myPhotoRemove(int $id){
        $em = $this->getDoctrine()->getManager();
        $myPhoto = $em->getRepository(Photo::class)->find($id);


        if($this->getUser() == $myPhoto->getUser())
        {
            $fileManager = new Filesystem();
            $fileManager->remove('images/hosting/'.$myPhoto->getFilename());
            if($fileManager->exists('images/hosting/'.$myPhoto->getFilename())){
                $this->addFlash('error', 'Nie udało się usunąć zdjęcia');
            }else{
                $em->remove($myPhoto);
                $em->flush();
                $this->addFlash('success', 'Usunięto zdjęcie');
            }
        } else {
            $this->addFlash('error', 'Nie usunieto zdjecia ponieważ nie jesteś jego właścicielem');
        }
        

        return $this->redirectToRoute('my_photos');

    }

}

templates/my/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Moje zdjęcia{% endblock %}

{% block content %}
    <div class="container">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
                    
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div> 
        {% endfor %} 

        <h1 class="mt-5 mb-4 h4">Najnowsze zdjęcia użytkowników</h1>

        <div class="mt-5">
            <div class="row">
                {% for photo in myPhotos %}
                    <div class="col-sm-12 col-lg-4">
                        <div class="card-deck">
                            <div class="card d-flex justify-content-between">
                                <div class="imageGallery1">
                                    <a href="/images/hosting/{{photo.filename}}"><img src="/images/hosting/{{photo.filename}}" class="card-img-top" alt=""></a>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">Wysłano: {{photo.uploadedAt|date('d.m.Y H:i:s')}}</small>
                                    <small class="text-muted">Dodał:{{photo.user.username}}</small>
                                    <p>
                                        {% if photo.user == app.user %}
                                            <a href="{{ path('my_photos_remove', {'id':photo.id}) }}" class="badge badge-danger">Usuń</a>   
                                            {% if photo.isPublic=='1' %}                                 
                                                <a href="{{ path('my_photos_set_visibility', {'id':photo.id, 'visibility': '0'})}}" class="badge badge-primary">Ustaw prywatne</a>
                                            {% else %}
                                                <a href="{{ path('my_photos_set_visibility', {'id':photo.id, 'visibility': '1'})}}" class="badge badge-succes">Ustaw jako publiczne</a>
                                            {% endif %}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}    
            </div>
        </div>

    </div>
{% endblock %}